static_library("ELFCommon") {
  output_name = "lldbELFProcessSupport"
  configs += [ "//llvm/utils/gn/build:lldb_code" ]
  deps = [
    "//lldb/source/Target",
    "//lldb/source/Utility",
    "//llvm/lib/Support",
  ]

  include_dirs = [ "//lldb/source" ]
  sources = [
    "AuxVector.cpp",
    "LinuxProcMaps.cpp",
  ]
}
